/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.85
 * Generated at: 2018-05-24 11:16:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class inscription_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/taglibs.jsp", Long.valueOf(1524656015116L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>Inscription</title>\r\n");
      out.write("<!-- inclusion Generale #################################################\"\" -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <title>Laboratoire Imsad</title>\r\n");
      out.write("\r\n");
      out.write("    <link href=\"presentation/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"presentation/css/metisMenu.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"presentation/css/accueilStyle.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"presentation/css/sb-admin-2.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"presentation/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("<!-- ################################################################################ -->\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t  \t.well\r\n");
      out.write("\t  \t{\r\n");
      out.write("\t  \t\tbox-shadow: 0px 0px 18px #888888;\r\n");
      out.write("\t  \t}\r\n");
      out.write("\t  \th4{\r\n");
      out.write("\t  \t\tpadding: 10px;\r\n");
      out.write("\t  \t}\r\n");
      out.write("\t  \th3{\r\n");
      out.write("\t  \t\tmargin-top: 0px;\r\n");
      out.write("\t  \t\tmargin-bottom: 30px;\r\n");
      out.write("\t  \t}\r\n");
      out.write("\t  \t[class*=\"col-\"]{\r\n");
      out.write("\t  \t\t/*border : 1px solid black;*/\r\n");
      out.write("\t  \t}\r\n");
      out.write("\t  \tlabel{\r\n");
      out.write("\t  \t\tpadding: 7px;\r\n");
      out.write("\t  \t}\r\n");
      out.write("\t  \t.bouton{\r\n");
      out.write("\t  \t\tpadding-right: 16px;\r\n");
      out.write("\t  \t}\r\n");
      out.write("\r\n");
      out.write("\t  \t.error {\r\n");
      out.write("      \t\tcolor: #a94442;\r\n");
      out.write("   \t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div align=\"center\" class=\" col-sm-12\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-12 entete\" align=\"center\"> \r\n");
      out.write("\t\t\t\t<img class=\"img-responsive\" src=\"presentation/img/logoFsac.png\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<h1> Bienvenue dans la page d'inscription de <br> <strong> <em> LIMSAD</em> </strong> </h1>\r\n");
      out.write("\t\t\t<h4><font color=\"red\">  *Vous étes sur le point de vous s'inscrire merci de remplire ces champs avec des informations correctes\r\n");
      out.write("\t\t\tou votre inscription sera rejeter*</font> </h4>\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md-offset-2 col-md-8 col-lg-offset-3 col-lg-6 well\">\r\n");
      out.write("\t\t\t<form id=\"signupForm\" method=\"post\" class=\"form-horizontal\" action=\"\">\r\n");
      out.write("\t\t\t\t<h3 align=\"center\"> Inscrivez-Vous </h3>\r\n");
      out.write("\t\t\t\t<p align=\"center\"> <font color=\"red\">");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("</font></p>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"col-sm-3\" for=\"nom\">Nom </label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"nom\" name=\"nom\" placeholder=\"Exemple : chafouai\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"col-sm-3\" for=\"prenom\">Prenom</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"prenom\" name=\"prenom\" placeholder=\"Exemple : said\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"col-sm-3\" for=\"email\">Email</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"email\" name=\"email\" placeholder=\"Exemple : nomprenom123@gmail.com\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"col-sm-3\" for=\"gsm\">GSM</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"gsm\" name=\"gsm\" placeholder=\"Exemple : 0685967412\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"col-sm-3\" for=\"adresse\">Adresse</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"adresse\" name=\"adresse\" placeholder=\"Exemple : Boulvard ibno sina ...\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"col-sm-3\" for=\"fonction\">Fonction</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t<select name=\"fonction\" id=\"fonction\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">Choisissez...</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"enseignant\" onclick=\"utilisateur()\">Enseignant Chercheur</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"doctorant\" onclick=\"doctorant()\">Doctorant</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-group\" id=\"demo\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"pull-right bouton\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-success\" name=\"signup\" value=\"Sign up\">Inscription</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div align=\"center\" class=\"col-sm-12\">\r\n");
      out.write("\t\t\t<footer>\r\n");
      out.write("\t\t\t\t<h5> &copy;Tous droit résèrver au Groupe de PFE SMS </h5>\r\n");
      out.write("\t\t\t</footer>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t    <script src=\"presentation/js/jquery-1.11.1.js\"></script>\r\n");
      out.write("\t    <script src=\"presentation/js/jquery.validate.js\"></script>\r\n");
      out.write("\t    <script src=\"presentation/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t    <script>\r\n");
      out.write("\t\t\tfunction utilisateur() {\r\n");
      out.write("\t\t\t\tvar xhttp = new XMLHttpRequest();\r\n");
      out.write("\t\t\t  \txhttp.onreadystatechange = function() {\r\n");
      out.write("\t\t\t    \tif (this.readyState == 4 && this.status == 200) {\r\n");
      out.write("\t\t\t      \tdocument.getElementById(\"demo\").innerHTML = this.responseText;\r\n");
      out.write("\t\t\t    \t}\r\n");
      out.write("\t\t\t \t};\r\n");
      out.write("\r\n");
      out.write("\t\t\t  \txhttp.open(\"GET\", \"presentation/html/utilisateurs.html\", true);\r\n");
      out.write("\t\t\t  \txhttp.send();\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\t\tfunction doctorant() {\r\n");
      out.write("\t\t\t  \tvar xhttp = new XMLHttpRequest();\r\n");
      out.write("\t\t\t  \txhttp.onreadystatechange = function() {\r\n");
      out.write("\t\t\t    \tif (this.readyState == 4 && this.status == 200) {\r\n");
      out.write("\t\t\t      \tdocument.getElementById(\"demo\").innerHTML = this.responseText;\r\n");
      out.write("\t\t\t    \t}\r\n");
      out.write("\t\t\t  \t};\r\n");
      out.write("\r\n");
      out.write("\t\t\t  \txhttp.open(\"GET\", \"presentation/html/doctorant.jsp\", true);\r\n");
      out.write("\t\t\t  \txhttp.send();\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t$( document ).ready( function () {\r\n");
      out.write("\t\t\t\t$( \"#signupForm\" ).validate( {\r\n");
      out.write("\t\t\t\t\trules: {\r\n");
      out.write("\t\t\t\t\t\tgrade : \"required\",\r\n");
      out.write("\t\t\t\t\t\tfonction : \"required\",\r\n");
      out.write("\t\t\t\t\t\tnom: \"required\",\r\n");
      out.write("\t\t\t\t\t\tprenom: \"required\",\r\n");
      out.write("\t\t\t\t\t\tgsm :{\r\n");
      out.write("\t\t\t\t\t\t\trequired : true,\r\n");
      out.write("\t\t\t\t\t\t\tnumber : true,\r\n");
      out.write("\t\t\t\t\t\t\tminlength : 10,\r\n");
      out.write("\t\t\t\t\t\t\tmaxlength : 10\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tcne: {\r\n");
      out.write("\t\t\t\t\t\t\trequired : true,\r\n");
      out.write("\t\t\t\t\t\t\tnumber : true,\r\n");
      out.write("\t\t\t\t\t\t\tminlength : 10,\r\n");
      out.write("\t\t\t\t\t\t\tmaxlength : 10\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\temail: {\r\n");
      out.write("\t\t\t\t\t\t\trequired: true,\r\n");
      out.write("\t\t\t\t\t\t\temail: true\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tmessages: {\r\n");
      out.write("\t\t\t\t\t\tgrade : \"choisissez votre grade\",\r\n");
      out.write("\t\t\t\t\t\tfonction : \"choisissez une fonction\",\r\n");
      out.write("\t\t\t\t\t\tnom: \"SVP rensignez votre nom \",\r\n");
      out.write("\t\t\t\t\t\tprenom: \"SVP rensignez votre prenom\",\r\n");
      out.write("\t\t\t\t\t\tgsm :{\r\n");
      out.write("\t\t\t\t\t\t\trequired : \"SVP saisissez votre numéro de tèlèphone\",\r\n");
      out.write("\t\t\t\t\t\t\tnumber : \"numéro n'est pas valide\",\r\n");
      out.write("\t\t\t\t\t\t\tminlength : \"un numéro valide doit comporte 10 chiffres\",\r\n");
      out.write("\t\t\t\t\t\t\tmaxlength : \"un numéro valide doit comporte 10 chiffres\",\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tcne: {\r\n");
      out.write("\t\t\t\t\t\t\trequired : \"SVP saisissez votre CNE\",\r\n");
      out.write("\t\t\t\t\t\t\tnumber : \"CNE n'est pas valide\",\r\n");
      out.write("\t\t\t\t\t\t\tminlength : \"un CNE valide doit comporte 10 chiffres\",\r\n");
      out.write("\t\t\t\t\t\t\tmaxlength : \"un CNE valide doit comporte 10 chiffres\",\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\temail: \"email invalide\"\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terrorElement: \"em\",\r\n");
      out.write("\t\t\t\t\terrorPlacement: function ( error, element ) {\r\n");
      out.write("\t\t\t\t\t\t// Add the `help-block` class to the error element\r\n");
      out.write("\t\t\t\t\t\terror.addClass( \"help-block\" );\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tif ( element.prop( \"type\" ) === \"checkbox\" ) {\r\n");
      out.write("\t\t\t\t\t\t\terror.insertAfter( element.parent( \"label\" ) );\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\terror.insertAfter( element );\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\thighlight: function ( element, errorClass, validClass ) {\r\n");
      out.write("\t\t\t\t\t\t$( element ).parents( \".col-sm-9\" ).addClass( \"has-error\" ).removeClass( \"has-success\" );\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tunhighlight: function (element, errorClass, validClass) {\r\n");
      out.write("\t\t\t\t\t\t$( element ).parents( \".col-sm-9\" ).addClass( \"has-success\" ).removeClass( \"has-error\" );\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t} );\r\n");
      out.write("\t\t\t} );\r\n");
      out.write("\t\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /WEB-INF/inscription.jsp(67,41) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${echec}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }
}
